from typing import Optional
"""
Career Dreamer — Taxonomy Data Layer
=====================================
Deterministic skill/role data powering the hybrid career matching engine.

- ACTIVITY_SKILL_MAP: maps user activities → weighted transferable skills
- ROLE_DATABASE: defines ~40 career roles with skill requirements
- SUBJECT_SKILL_BASELINE: derives implicit skills from academic background
"""

# ──────────────────────────────────────────────────────────────────────────────
# ACTIVITY → SKILL MAPPINGS
# Each key is a lowercase keyword/phrase found in user input.
# Value is a dict of skill_name → weight (1-10).
# Multiple matches are aggregated by the skill extractor.
# ──────────────────────────────────────────────────────────────────────────────

ACTIVITY_SKILL_MAP: dict[str, dict[str, float]] = {
    # Leadership / Management activities
    "managed": {"leadership": 7, "stakeholder_management": 6, "coordination": 7, "communication": 6},
    "led": {"leadership": 8, "decision_making": 7, "team_management": 7, "communication": 6},
    "organized": {"coordination": 8, "event_management": 7, "planning": 7, "communication": 5},
    "president": {"leadership": 9, "public_speaking": 7, "decision_making": 8, "stakeholder_management": 7},
    "captain": {"leadership": 8, "team_management": 7, "decision_making": 7, "resilience": 6},
    "club": {"teamwork": 6, "communication": 5, "coordination": 5, "leadership": 4},
    "volunteer": {"empathy": 6, "communication": 6, "teamwork": 7, "social_awareness": 6},
    "mentored": {"leadership": 7, "communication": 8, "teaching": 7, "empathy": 6},
    "coordinated": {"coordination": 8, "planning": 7, "communication": 6, "multitasking": 6},
    "event": {"event_management": 7, "coordination": 7, "communication": 6, "planning": 6},
    "hackathon": {"problem_solving": 8, "teamwork": 7, "coding": 7, "rapid_prototyping": 7, "creativity": 6},
    "competition": {"problem_solving": 7, "analytical_thinking": 6, "resilience": 6, "competitiveness": 5},

    # Technical / Development activities
    "built": {"problem_solving": 7, "execution": 7, "coding": 6, "product_thinking": 5},
    "developed": {"coding": 7, "problem_solving": 7, "systems_thinking": 6, "debugging": 5},
    "website": {"frontend_development": 8, "html_css": 7, "ui_design": 5, "problem_solving": 6},
    "web app": {"frontend_development": 8, "backend_development": 7, "database": 5, "api_design": 5},
    "mobile app": {"mobile_development": 8, "ui_design": 6, "problem_solving": 7, "api_design": 5},
    "app": {"coding": 7, "product_thinking": 6, "problem_solving": 7, "debugging": 6},
    "coded": {"coding": 8, "debugging": 6, "problem_solving": 7, "logical_thinking": 6},
    "programmed": {"coding": 8, "debugging": 7, "algorithmic_thinking": 7, "logical_thinking": 7},
    "software": {"coding": 7, "systems_thinking": 6, "debugging": 6, "software_engineering": 7},
    "api": {"api_design": 8, "backend_development": 7, "systems_thinking": 6, "database": 5},
    "database": {"database": 8, "sql": 7, "data_modeling": 6, "backend_development": 5},
    "deployed": {"devops": 7, "cloud_computing": 6, "systems_thinking": 6, "execution": 6},
    "automated": {"automation": 8, "scripting": 7, "problem_solving": 6, "systems_thinking": 6},
    "tested": {"testing": 7, "quality_assurance": 6, "debugging": 6, "attention_to_detail": 6},
    "debug": {"debugging": 8, "problem_solving": 7, "analytical_thinking": 6, "patience": 5},
    "algorithm": {"algorithmic_thinking": 8, "problem_solving": 8, "logical_thinking": 7, "mathematics": 6},
    "open source": {"collaboration": 7, "coding": 7, "communication": 6, "git": 6},
    "github": {"git": 7, "coding": 6, "collaboration": 5, "documentation": 5},
    "linux": {"systems_administration": 6, "command_line": 7, "devops": 5, "troubleshooting": 6},
    "cloud": {"cloud_computing": 8, "devops": 6, "systems_thinking": 6, "infrastructure": 6},
    "docker": {"devops": 7, "cloud_computing": 6, "systems_thinking": 6, "containerization": 7},
    "kubernetes": {"devops": 8, "cloud_computing": 7, "systems_thinking": 7, "infrastructure": 7},

    # Data / AI activities
    "data": {"data_analysis": 7, "analytical_thinking": 7, "statistics": 5, "problem_solving": 6},
    "machine learning": {"machine_learning": 9, "mathematics": 7, "python": 7, "data_analysis": 7},
    "deep learning": {"deep_learning": 9, "machine_learning": 8, "mathematics": 8, "python": 7},
    "neural network": {"deep_learning": 8, "mathematics": 7, "python": 7, "machine_learning": 7},
    "ai": {"machine_learning": 7, "problem_solving": 7, "python": 6, "mathematics": 6},
    "nlp": {"nlp": 8, "machine_learning": 7, "python": 7, "linguistics": 5},
    "computer vision": {"computer_vision": 8, "deep_learning": 7, "python": 7, "mathematics": 6},
    "model": {"machine_learning": 7, "data_analysis": 6, "mathematics": 6, "python": 6},
    "analytics": {"data_analysis": 8, "statistics": 7, "visualization": 6, "business_intelligence": 6},
    "visualization": {"visualization": 7, "data_analysis": 6, "communication": 5, "design_thinking": 4},
    "statistics": {"statistics": 8, "mathematics": 7, "analytical_thinking": 7, "data_analysis": 6},
    "sql": {"sql": 8, "database": 7, "data_analysis": 6, "backend_development": 4},
    "python": {"python": 8, "coding": 6, "scripting": 6, "problem_solving": 5},
    "excel": {"data_analysis": 6, "business_intelligence": 5, "analytical_thinking": 5, "reporting": 5},
    "tableau": {"visualization": 7, "data_analysis": 6, "business_intelligence": 6, "reporting": 5},
    "power bi": {"visualization": 7, "data_analysis": 6, "business_intelligence": 6, "reporting": 5},

    # Design activities
    "designed": {"design_thinking": 7, "creativity": 7, "ui_design": 6, "problem_solving": 5},
    "ui": {"ui_design": 8, "design_thinking": 7, "frontend_development": 5, "user_research": 5},
    "ux": {"ux_design": 8, "user_research": 7, "design_thinking": 7, "empathy": 6},
    "figma": {"ui_design": 7, "design_thinking": 6, "prototyping": 6, "creativity": 5},
    "prototype": {"prototyping": 7, "design_thinking": 6, "product_thinking": 6, "creativity": 5},
    "graphic": {"graphic_design": 7, "creativity": 7, "visual_communication": 6, "design_thinking": 5},

    # Business / Product activities
    "startup": {"entrepreneurship": 8, "product_thinking": 7, "leadership": 6, "risk_taking": 6},
    "business": {"business_acumen": 7, "strategic_thinking": 6, "communication": 6, "analytical_thinking": 5},
    "marketing": {"marketing": 8, "communication": 7, "analytical_thinking": 5, "creativity": 6},
    "sales": {"communication": 8, "negotiation": 7, "persuasion": 7, "relationship_building": 6},
    "product": {"product_thinking": 8, "strategic_thinking": 7, "communication": 6, "user_research": 5},
    "strategy": {"strategic_thinking": 8, "analytical_thinking": 7, "decision_making": 7, "business_acumen": 6},
    "finance": {"financial_analysis": 8, "analytical_thinking": 7, "mathematics": 6, "business_acumen": 6},
    "consulting": {"analytical_thinking": 8, "communication": 8, "strategic_thinking": 7, "problem_solving": 7},
    "project management": {"project_management": 8, "planning": 7, "communication": 7, "leadership": 6},
    "agile": {"agile_methodology": 7, "project_management": 6, "teamwork": 6, "communication": 5},
    "scrum": {"agile_methodology": 7, "project_management": 6, "teamwork": 6, "communication": 5},

    # Research / Academic activities
    "research": {"research": 8, "analytical_thinking": 7, "critical_thinking": 7, "writing": 6},
    "published": {"research": 8, "writing": 8, "critical_thinking": 7, "analytical_thinking": 7},
    "paper": {"research": 7, "writing": 7, "analytical_thinking": 6, "critical_thinking": 6},
    "thesis": {"research": 8, "writing": 7, "analytical_thinking": 7, "critical_thinking": 7},
    "lab": {"research": 7, "attention_to_detail": 6, "analytical_thinking": 6, "problem_solving": 5},
    "experiment": {"research": 7, "analytical_thinking": 7, "critical_thinking": 6, "data_analysis": 5},

    # Engineering domain activities
    "robotics": {"robotics": 8, "embedded_systems": 7, "problem_solving": 7, "mathematics": 6},
    "circuit": {"electronics": 8, "circuit_design": 8, "mathematics": 6, "problem_solving": 6},
    "embedded": {"embedded_systems": 8, "coding": 6, "electronics": 6, "systems_thinking": 6},
    "iot": {"iot": 8, "embedded_systems": 7, "cloud_computing": 5, "systems_thinking": 6},
    "cad": {"cad_design": 8, "mechanical_engineering": 6, "attention_to_detail": 6, "spatial_reasoning": 6},
    "solidworks": {"cad_design": 7, "mechanical_engineering": 7, "3d_modeling": 7, "engineering_analysis": 5},
    "autocad": {"cad_design": 7, "drafting": 7, "civil_engineering": 5, "spatial_reasoning": 6},
    "manufacturing": {"manufacturing": 7, "quality_control": 6, "process_optimization": 6, "attention_to_detail": 5},

    # Cybersecurity
    "security": {"cybersecurity": 7, "networking": 6, "analytical_thinking": 6, "risk_assessment": 6},
    "hacking": {"cybersecurity": 8, "networking": 7, "problem_solving": 7, "ethical_hacking": 8},
    "penetration": {"ethical_hacking": 8, "cybersecurity": 8, "networking": 7, "problem_solving": 7},
    "firewall": {"networking": 7, "cybersecurity": 7, "systems_administration": 6, "infrastructure": 5},
    "encryption": {"cybersecurity": 7, "cryptography": 8, "mathematics": 6, "security_engineering": 6},

    # Communication / Soft skills indicators
    "presented": {"public_speaking": 8, "communication": 7, "confidence": 6, "storytelling": 5},
    "wrote": {"writing": 7, "communication": 6, "critical_thinking": 5, "research": 4},
    "taught": {"teaching": 8, "communication": 8, "patience": 6, "empathy": 5},
    "tutored": {"teaching": 7, "communication": 7, "patience": 6, "empathy": 5},
    "collaborated": {"teamwork": 8, "communication": 7, "conflict_resolution": 5, "adaptability": 5},
    "freelance": {"self_management": 7, "communication": 6, "entrepreneurship": 5, "time_management": 6},
    "internship": {"professional_experience": 7, "communication": 5, "teamwork": 5, "adaptability": 6},
    "intern": {"professional_experience": 6, "communication": 5, "teamwork": 5, "adaptability": 6},

    # Healthcare / Medical activities
    "doctor": {"medical_knowledge": 8, "empathy": 6, "attention_to_detail": 5, "decision_making": 7},
    "medical": {"medical_knowledge": 8, "attention_to_detail": 6, "empathy": 5},
    "patient": {"empathy": 8, "patient_care": 8, "communication": 7},
    "diagnose": {"medical_knowledge": 8, "analytical_thinking": 7, "decision_making": 6},
    "treatment": {"medical_knowledge": 7, "patient_care": 7, "attention_to_detail": 6},
    "clinic": {"patient_care": 7, "coordination": 5, "empathy": 5},

    # Education / Teaching activities
    "teacher": {"teaching": 8, "communication": 7, "leadership": 5, "patience": 7},
    "educat": {"teaching": 8, "communication": 7, "planning": 6},
    "classroom": {"teaching": 7, "leadership": 6, "coordination": 6},
    "lesson": {"planning": 7, "teaching": 7, "writing": 5},
    "student": {"communication": 6, "teaching": 6, "empathy": 6},
    "teach": {"teaching": 8, "communication": 7, "empathy": 5},
}


# ──────────────────────────────────────────────────────────────────────────────
# SUBJECT → BASELINE SKILL MAPPING
# Derives implicit skills from academic background / field of study.
# ──────────────────────────────────────────────────────────────────────────────

SUBJECT_SKILL_BASELINE: dict[str, dict[str, float]] = {
    "cse": {"coding": 7, "algorithmic_thinking": 7, "problem_solving": 7, "systems_thinking": 6, "database": 5, "mathematics": 5, "logical_thinking": 7},
    "computer science": {"coding": 7, "algorithmic_thinking": 7, "problem_solving": 7, "systems_thinking": 6, "database": 5, "mathematics": 5, "logical_thinking": 7},
    "it": {"coding": 6, "networking": 6, "database": 6, "systems_administration": 5, "problem_solving": 6, "communication": 5},
    "information technology": {"coding": 6, "networking": 6, "database": 6, "systems_administration": 5, "problem_solving": 6},
    "software": {"coding": 7, "software_engineering": 7, "systems_thinking": 6, "debugging": 6, "testing": 5, "problem_solving": 7},
    "ece": {"electronics": 7, "circuit_design": 6, "embedded_systems": 6, "mathematics": 6, "signal_processing": 5, "problem_solving": 6},
    "electronics": {"electronics": 7, "circuit_design": 6, "embedded_systems": 6, "mathematics": 6, "problem_solving": 6},
    "electrical": {"electronics": 6, "power_systems": 6, "mathematics": 7, "circuit_design": 5, "problem_solving": 6},
    "mechanical": {"mechanical_engineering": 7, "cad_design": 6, "mathematics": 6, "physics": 6, "problem_solving": 6, "manufacturing": 5},
    "civil": {"civil_engineering": 7, "drafting": 6, "mathematics": 6, "project_management": 5, "spatial_reasoning": 6},
    "data science": {"data_analysis": 8, "machine_learning": 7, "statistics": 7, "python": 7, "mathematics": 7, "visualization": 5},
    "ai": {"machine_learning": 7, "deep_learning": 6, "mathematics": 7, "python": 7, "problem_solving": 7},
    "aiml": {"machine_learning": 7, "deep_learning": 6, "mathematics": 7, "python": 7, "problem_solving": 7},
    "machine learning": {"machine_learning": 8, "deep_learning": 6, "mathematics": 7, "python": 7, "statistics": 6},
    "mba": {"business_acumen": 7, "strategic_thinking": 7, "leadership": 6, "communication": 6, "financial_analysis": 5, "marketing": 5},
    "business": {"business_acumen": 7, "strategic_thinking": 6, "communication": 6, "financial_analysis": 5, "analytical_thinking": 5},
    "management": {"leadership": 6, "project_management": 6, "communication": 6, "strategic_thinking": 6, "team_management": 5},
    "medical": {"medical_knowledge": 8, "empathy": 7, "critical_thinking": 6, "attention_to_detail": 7, "communication": 6},
    "mbbs": {"medical_knowledge": 8, "empathy": 7, "critical_thinking": 7, "attention_to_detail": 7, "communication": 6},
    "nursing": {"patient_care": 8, "empathy": 7, "communication": 7, "teamwork": 6, "attention_to_detail": 6},
    "design": {"design_thinking": 7, "creativity": 7, "ui_design": 6, "visual_communication": 6, "prototyping": 5},
    "ux": {"ux_design": 8, "user_research": 7, "design_thinking": 7, "empathy": 6, "prototyping": 6},
    "cyber": {"cybersecurity": 7, "networking": 6, "ethical_hacking": 5, "risk_assessment": 5, "problem_solving": 6},
    "security": {"cybersecurity": 7, "networking": 6, "risk_assessment": 5, "analytical_thinking": 6},
    "robotics": {"robotics": 7, "embedded_systems": 6, "coding": 5, "mathematics": 6, "problem_solving": 6},
    "automation": {"automation": 7, "embedded_systems": 6, "coding": 5, "systems_thinking": 6},
    "commerce": {"financial_analysis": 6, "business_acumen": 6, "accounting": 6, "analytical_thinking": 5, "communication": 5},
    "arts": {"creativity": 7, "communication": 6, "critical_thinking": 6, "writing": 5, "research": 5},
    "law": {"critical_thinking": 7, "writing": 7, "communication": 7, "analytical_thinking": 6, "research": 6},
    "pharmacy": {"pharmaceutical_knowledge": 7, "chemistry": 6, "attention_to_detail": 7, "research": 5, "analytical_thinking": 5},
    "biotechnology": {"research": 7, "data_analysis": 5, "chemistry": 5, "analytical_thinking": 6, "problem_solving": 5},
    "mathematics": {"mathematics": 8, "analytical_thinking": 8, "logical_thinking": 7, "statistics": 6, "problem_solving": 7},
    "physics": {"mathematics": 7, "analytical_thinking": 7, "problem_solving": 7, "research": 6, "physics": 8},
    "chemistry": {"chemistry": 8, "research": 6, "analytical_thinking": 6, "attention_to_detail": 6, "laboratory": 6},
}


# ──────────────────────────────────────────────────────────────────────────────
# ROLE DATABASE
# Each role has: required skills (weights), salary range, growth trajectory,
# description, typical degree, industry demand, personality fit, roadmap.
# ──────────────────────────────────────────────────────────────────────────────

ROLE_DATABASE: dict[str, dict] = {
    "Software Engineer": {
        "skills": {"coding": 9, "problem_solving": 8, "systems_thinking": 7, "debugging": 7, "algorithmic_thinking": 7, "software_engineering": 7, "database": 5, "communication": 4, "teamwork": 4},
        "salary": {"entry": "$70,000", "mid": "$120,000", "senior": "$180,000+"},
        "growth": ["Junior Developer", "Software Engineer", "Senior Engineer", "Staff Engineer", "Principal Engineer"],
        "description": "Design, build, and maintain scalable software systems across the full stack.",
        "typical_degree": "Bachelor's in CS/IT/Software Engineering",
        "demand": "very_high",
        "personality": ["analytical", "detail-oriented", "collaborative"],
        "roadmap": [
            {"month": 1, "title": "Programming Foundations", "tasks": ["Master a core language (Python/Java/JS)", "Learn Git workflows", "Build CLI tools"], "stack": "Python, Git, VS Code", "concepts": "OOP, Data Structures, Version Control"},
            {"month": 2, "title": "Data Structures & Algorithms", "tasks": ["Solve 50+ LeetCode problems", "Implement common data structures", "Study time/space complexity"], "stack": "Python, LeetCode", "concepts": "Arrays, Trees, Graphs, Dynamic Programming"},
            {"month": 3, "title": "Web Development", "tasks": ["Build a full-stack web app", "Learn REST API design", "Implement authentication"], "stack": "React, Node.js, PostgreSQL", "concepts": "HTTP, REST, MVC, Database Design"},
            {"month": 4, "title": "System Design", "tasks": ["Design URL shortener", "Study distributed systems basics", "Learn caching strategies"], "stack": "Redis, Docker, AWS", "concepts": "Scalability, Load Balancing, CAP Theorem"},
            {"month": 5, "title": "Testing & DevOps", "tasks": ["Write unit/integration tests", "Set up CI/CD pipeline", "Deploy to cloud"], "stack": "Jest, GitHub Actions, AWS/GCP", "concepts": "TDD, CI/CD, Container Orchestration"},
            {"month": 6, "title": "Interview & Portfolio", "tasks": ["Mock interviews", "Polish GitHub portfolio", "Apply to 20+ positions"], "stack": "LeetCode, LinkedIn, GitHub", "concepts": "Behavioral Interviews, System Design Interviews"},
        ],
    },
    "Frontend Engineer": {
        "skills": {"frontend_development": 9, "html_css": 8, "ui_design": 7, "coding": 7, "problem_solving": 6, "design_thinking": 5, "debugging": 6, "communication": 5, "user_research": 4},
        "salary": {"entry": "$65,000", "mid": "$110,000", "senior": "$165,000+"},
        "growth": ["Junior Frontend Dev", "Frontend Engineer", "Senior Frontend Engineer", "Lead Frontend Engineer", "Frontend Architect"],
        "description": "Build responsive, performant, and accessible user interfaces that delight users.",
        "typical_degree": "Bachelor's in CS/IT/Design",
        "demand": "high",
        "personality": ["creative", "detail-oriented", "user-focused"],
        "roadmap": [
            {"month": 1, "title": "HTML, CSS & JS Mastery", "tasks": ["Build 5 responsive landing pages", "Master Flexbox and Grid", "Learn modern JavaScript (ES6+)"], "stack": "HTML5, CSS3, JavaScript", "concepts": "Responsive Design, Accessibility, DOM"},
            {"month": 2, "title": "React & Component Design", "tasks": ["Build a React SPA", "Learn state management", "Implement routing"], "stack": "React 18, TypeScript, Vite", "concepts": "Component Architecture, Hooks, Virtual DOM"},
            {"month": 3, "title": "Advanced UI/UX", "tasks": ["Implement animations", "Performance optimization", "Accessibility auditing"], "stack": "Framer Motion, Lighthouse, ARIA", "concepts": "Web Performance, A11y, Design Systems"},
            {"month": 4, "title": "Full Stack Integration", "tasks": ["Connect to REST/GraphQL APIs", "Implement auth flows", "State management at scale"], "stack": "Next.js, GraphQL, Zustand", "concepts": "SSR, API Integration, Auth Patterns"},
            {"month": 5, "title": "Testing & Tooling", "tasks": ["Write component tests", "E2E testing setup", "Build a design system"], "stack": "Vitest, Playwright, Storybook", "concepts": "Testing Pyramid, Component Libraries"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Build stunning portfolio site", "Contribute to open source", "Interview preparation"], "stack": "Vercel, GitHub, Figma", "concepts": "Portfolio Design, Technical Interviews"},
        ],
    },
    "Backend Engineer": {
        "skills": {"backend_development": 9, "database": 8, "api_design": 8, "coding": 8, "systems_thinking": 7, "devops": 5, "problem_solving": 7, "debugging": 6, "security_engineering": 4},
        "salary": {"entry": "$72,000", "mid": "$125,000", "senior": "$185,000+"},
        "growth": ["Junior Backend Dev", "Backend Engineer", "Senior Backend Engineer", "Principal Engineer", "Distinguished Engineer"],
        "description": "Build robust server-side systems, APIs, and data pipelines that power applications at scale.",
        "typical_degree": "Bachelor's in CS/IT",
        "demand": "very_high",
        "personality": ["systematic", "analytical", "performance-minded"],
        "roadmap": [
            {"month": 1, "title": "Server-Side Fundamentals", "tasks": ["Learn Python/Node.js backend", "Build REST APIs", "Database fundamentals"], "stack": "Python, FastAPI, PostgreSQL", "concepts": "REST, CRUD, SQL Fundamentals"},
            {"month": 2, "title": "Database Mastery", "tasks": ["Advanced SQL queries", "NoSQL databases", "Database optimization"], "stack": "PostgreSQL, MongoDB, Redis", "concepts": "Indexing, Normalization, Caching"},
            {"month": 3, "title": "API & Microservices", "tasks": ["GraphQL implementation", "Microservice architecture", "Message queues"], "stack": "GraphQL, RabbitMQ, Docker", "concepts": "API Gateway, Event-Driven Architecture"},
            {"month": 4, "title": "Security & Auth", "tasks": ["Implement OAuth2/JWT", "Security best practices", "Rate limiting & CORS"], "stack": "OAuth2, JWT, Helmet", "concepts": "Authentication, Authorization, OWASP"},
            {"month": 5, "title": "Cloud & DevOps", "tasks": ["Deploy to AWS/GCP", "Set up CI/CD", "Container orchestration"], "stack": "AWS, Docker, Kubernetes", "concepts": "Cloud Architecture, Infrastructure as Code"},
            {"month": 6, "title": "Scale & Interview Prep", "tasks": ["Load testing", "System design practice", "Mock interviews"], "stack": "k6, LeetCode, System Design Primer", "concepts": "Horizontal Scaling, Distributed Systems"},
        ],
    },
    "Full Stack Developer": {
        "skills": {"frontend_development": 7, "backend_development": 7, "coding": 8, "database": 6, "api_design": 6, "problem_solving": 7, "debugging": 6, "devops": 4, "ui_design": 4},
        "salary": {"entry": "$68,000", "mid": "$115,000", "senior": "$170,000+"},
        "growth": ["Junior Full Stack Dev", "Full Stack Developer", "Senior Full Stack Dev", "Tech Lead", "CTO"],
        "description": "Build end-to-end web applications spanning frontend, backend, and deployment.",
        "typical_degree": "Bachelor's in CS/IT",
        "demand": "very_high",
        "personality": ["versatile", "curious", "fast-learner"],
        "roadmap": [
            {"month": 1, "title": "Frontend Foundations", "tasks": ["HTML/CSS/JS mastery", "Build responsive layouts", "Learn React basics"], "stack": "HTML5, CSS3, React", "concepts": "Component Model, Responsive Design"},
            {"month": 2, "title": "Backend Foundations", "tasks": ["Build REST APIs", "Database design", "Authentication"], "stack": "Node.js, Express, MongoDB", "concepts": "REST, CRUD, Auth Flows"},
            {"month": 3, "title": "Full Stack Integration", "tasks": ["Connect frontend to backend", "Implement full CRUD app", "File uploads & storage"], "stack": "React, Node.js, Cloudinary", "concepts": "API Integration, File I/O"},
            {"month": 4, "title": "Advanced Patterns", "tasks": ["State management", "Real-time features (WebSocket)", "Performance optimization"], "stack": "Redux, Socket.io, Redis", "concepts": "Real-time Systems, Caching"},
            {"month": 5, "title": "Deployment & DevOps", "tasks": ["CI/CD pipelines", "Docker containerization", "Cloud deployment"], "stack": "Docker, GitHub Actions, Vercel", "concepts": "CI/CD, Containers, Cloud"},
            {"month": 6, "title": "Portfolio & Launch", "tasks": ["Build 2 production apps", "Technical blog writing", "Interview preparation"], "stack": "Next.js, Vercel, GitHub", "concepts": "Portfolio, System Design"},
        ],
    },
    "Data Scientist": {
        "skills": {"data_analysis": 9, "machine_learning": 8, "statistics": 8, "python": 8, "mathematics": 7, "visualization": 6, "communication": 5, "sql": 5, "problem_solving": 7},
        "salary": {"entry": "$75,000", "mid": "$130,000", "senior": "$190,000+"},
        "growth": ["Junior Data Scientist", "Data Scientist", "Senior Data Scientist", "Lead Data Scientist", "Chief Data Scientist"],
        "description": "Extract insights from complex data using statistical analysis and machine learning.",
        "typical_degree": "Master's in Data Science/Statistics/CS",
        "demand": "very_high",
        "personality": ["analytical", "curious", "detail-oriented"],
        "roadmap": [
            {"month": 1, "title": "Python & Statistics", "tasks": ["Python for data science", "Descriptive statistics", "Probability theory"], "stack": "Python, NumPy, Pandas", "concepts": "Distributions, Hypothesis Testing"},
            {"month": 2, "title": "Data Analysis & Viz", "tasks": ["Exploratory data analysis", "Dashboard creation", "SQL mastery"], "stack": "Matplotlib, Seaborn, SQL", "concepts": "EDA, Data Cleaning, Storytelling"},
            {"month": 3, "title": "Machine Learning", "tasks": ["Supervised learning models", "Cross-validation", "Feature engineering"], "stack": "Scikit-learn, XGBoost", "concepts": "Regression, Classification, Ensemble"},
            {"month": 4, "title": "Advanced ML", "tasks": ["Neural networks", "NLP basics", "Deep learning frameworks"], "stack": "TensorFlow, PyTorch, Hugging Face", "concepts": "Deep Learning, Transfer Learning"},
            {"month": 5, "title": "MLOps & Production", "tasks": ["Model deployment", "A/B testing", "ML pipelines"], "stack": "MLflow, FastAPI, Docker", "concepts": "Model Serving, Monitoring, Drift"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Kaggle competitions", "End-to-end project", "Interview prep"], "stack": "Kaggle, GitHub, Streamlit", "concepts": "Case Studies, Business Impact"},
        ],
    },
    "ML Engineer": {
        "skills": {"machine_learning": 9, "coding": 8, "python": 8, "deep_learning": 7, "mathematics": 7, "data_analysis": 6, "systems_thinking": 6, "devops": 5, "problem_solving": 7},
        "salary": {"entry": "$80,000", "mid": "$140,000", "senior": "$200,000+"},
        "growth": ["Junior ML Engineer", "ML Engineer", "Senior ML Engineer", "ML Architect", "Head of AI"],
        "description": "Design, train, and deploy production machine learning systems at scale.",
        "typical_degree": "Master's/PhD in CS/AI/ML",
        "demand": "very_high",
        "personality": ["analytical", "research-oriented", "systematic"],
        "roadmap": [
            {"month": 1, "title": "ML Foundations", "tasks": ["Implement ML from scratch", "Study linear algebra", "Learn optimization theory"], "stack": "Python, NumPy, Jupyter", "concepts": "Gradient Descent, Loss Functions, Regularization"},
            {"month": 2, "title": "Deep Learning", "tasks": ["Build CNNs and RNNs", "Transfer learning", "Fine-tune pretrained models"], "stack": "PyTorch, TensorFlow", "concepts": "Backpropagation, Architectures, Attention"},
            {"month": 3, "title": "NLP & LLMs", "tasks": ["Text classification", "Transformer models", "Fine-tune LLMs"], "stack": "Hugging Face, LangChain", "concepts": "Embeddings, Transformers, RAG"},
            {"month": 4, "title": "ML Systems", "tasks": ["Build training pipelines", "Feature stores", "Model versioning"], "stack": "MLflow, DVC, Weights & Biases", "concepts": "ML Pipelines, Feature Engineering"},
            {"month": 5, "title": "Production ML", "tasks": ["Model serving at scale", "A/B testing ML models", "Monitoring & alerting"], "stack": "TorchServe, Kubernetes, Prometheus", "concepts": "Model Serving, Drift Detection, Scaling"},
            {"month": 6, "title": "Research & Career", "tasks": ["Reproduce 2 papers", "Build end-to-end ML app", "Interview preparation"], "stack": "arXiv, GitHub, LeetCode", "concepts": "Research Methodology, ML Design Interviews"},
        ],
    },
    "Data Engineer": {
        "skills": {"database": 9, "sql": 8, "python": 7, "data_analysis": 6, "cloud_computing": 7, "systems_thinking": 7, "coding": 6, "devops": 5, "problem_solving": 6},
        "salary": {"entry": "$72,000", "mid": "$125,000", "senior": "$175,000+"},
        "growth": ["Junior Data Engineer", "Data Engineer", "Senior Data Engineer", "Staff Data Engineer", "Principal Data Engineer"],
        "description": "Build and maintain data pipelines, warehouses, and infrastructure for analytics.",
        "typical_degree": "Bachelor's in CS/IT/Data Science",
        "demand": "very_high",
        "personality": ["systematic", "detail-oriented", "infrastructure-minded"],
        "roadmap": [
            {"month": 1, "title": "SQL & Database Design", "tasks": ["Advanced SQL", "Schema design", "Indexing strategies"], "stack": "PostgreSQL, MySQL", "concepts": "Normalization, Query Optimization"},
            {"month": 2, "title": "Python Data Engineering", "tasks": ["ETL scripts", "Data validation", "Workflow orchestration"], "stack": "Python, Pandas, Airflow", "concepts": "ETL, Data Quality, Scheduling"},
            {"month": 3, "title": "Cloud Data Platforms", "tasks": ["Cloud data warehouses", "Serverless data pipelines", "Data lake design"], "stack": "BigQuery, Snowflake, AWS S3", "concepts": "Data Warehousing, Data Lakes"},
            {"month": 4, "title": "Streaming & Real-time", "tasks": ["Event streaming", "Real-time analytics", "Change data capture"], "stack": "Kafka, Spark Streaming, Debezium", "concepts": "Stream Processing, Event Sourcing"},
            {"month": 5, "title": "Infrastructure & DevOps", "tasks": ["Containerize pipelines", "Infrastructure as code", "Monitoring"], "stack": "Docker, Terraform, Datadog", "concepts": "IaC, Observability, SLAs"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["End-to-end pipeline project", "Data modeling portfolio", "Interview preparation"], "stack": "dbt, GitHub, LeetCode", "concepts": "Data Modeling, System Design"},
        ],
    },
    "DevOps Engineer": {
        "skills": {"devops": 9, "cloud_computing": 8, "systems_administration": 7, "coding": 6, "automation": 7, "infrastructure": 7, "containerization": 7, "systems_thinking": 6, "problem_solving": 6},
        "salary": {"entry": "$70,000", "mid": "$125,000", "senior": "$175,000+"},
        "growth": ["Junior DevOps", "DevOps Engineer", "Senior DevOps", "SRE", "Platform Architect"],
        "description": "Automate infrastructure, manage CI/CD pipelines, and ensure system reliability at scale.",
        "typical_degree": "Bachelor's in CS/IT",
        "demand": "high",
        "personality": ["systematic", "automation-focused", "resilient"],
        "roadmap": [
            {"month": 1, "title": "Linux & Networking", "tasks": ["Linux administration", "Networking fundamentals", "Bash scripting"], "stack": "Linux, Bash, TCP/IP", "concepts": "File Systems, DNS, Firewalls"},
            {"month": 2, "title": "Containers & Orchestration", "tasks": ["Docker mastery", "Kubernetes basics", "Helm charts"], "stack": "Docker, Kubernetes, Helm", "concepts": "Containerization, Pods, Services"},
            {"month": 3, "title": "CI/CD & Automation", "tasks": ["Build CI/CD pipelines", "Automated testing", "GitOps workflows"], "stack": "GitHub Actions, Jenkins, ArgoCD", "concepts": "CI/CD, GitOps, Blue-Green Deployments"},
            {"month": 4, "title": "Cloud Infrastructure", "tasks": ["Multi-cloud setup", "Infrastructure as Code", "Cost optimization"], "stack": "AWS, Terraform, Pulumi", "concepts": "IaC, Cloud Architecture, FinOps"},
            {"month": 5, "title": "Monitoring & SRE", "tasks": ["Observability stack", "Alerting and SLOs", "Incident management"], "stack": "Prometheus, Grafana, PagerDuty", "concepts": "SRE Principles, SLOs, Postmortems"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Document infrastructure projects", "Contribute to IaC repos", "Interview preparation"], "stack": "GitHub, Terraform Registry, LeetCode", "concepts": "System Design, SRE Interviews"},
        ],
    },
    "Product Manager": {
        "skills": {"product_thinking": 9, "communication": 8, "strategic_thinking": 8, "user_research": 7, "analytical_thinking": 7, "leadership": 6, "data_analysis": 5, "design_thinking": 5, "business_acumen": 6},
        "salary": {"entry": "$80,000", "mid": "$135,000", "senior": "$200,000+"},
        "growth": ["Associate PM", "Product Manager", "Senior PM", "Director of Product", "VP of Product"],
        "description": "Define product vision, prioritize features, and drive cross-functional teams to ship impactful products.",
        "typical_degree": "Bachelor's in CS/Business/Engineering",
        "demand": "high",
        "personality": ["visionary", "empathetic", "data-driven"],
        "roadmap": [
            {"month": 1, "title": "Product Foundations", "tasks": ["Product thinking frameworks", "User research methods", "Competitive analysis"], "stack": "Notion, Figma, Miro", "concepts": "Product-Market Fit, Jobs-to-be-Done"},
            {"month": 2, "title": "User Research & Discovery", "tasks": ["Conduct user interviews", "Build personas", "Journey mapping"], "stack": "Maze, Hotjar, Google Analytics", "concepts": "Qualitative Research, Empathy Maps"},
            {"month": 3, "title": "Strategy & Prioritization", "tasks": ["PRD writing", "Roadmap creation", "Stakeholder alignment"], "stack": "Jira, Linear, Confluence", "concepts": "RICE, MoSCoW, OKRs"},
            {"month": 4, "title": "Data-Driven PM", "tasks": ["Define KPIs and metrics", "A/B testing", "Funnel analysis"], "stack": "Mixpanel, Amplitude, SQL", "concepts": "Product Analytics, Experimentation"},
            {"month": 5, "title": "Execution & Launch", "tasks": ["Sprint planning", "Cross-functional leadership", "Go-to-market strategy"], "stack": "Jira, Slack, Loom", "concepts": "Agile/Scrum, GTM, Launch Planning"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Build PM portfolio", "Case study preparation", "Mock interviews"], "stack": "Portfolio Site, Notion, LinkedIn", "concepts": "PM Interviews, Estimation Questions"},
        ],
    },
    "UX Designer": {
        "skills": {"ux_design": 9, "ui_design": 8, "user_research": 8, "design_thinking": 8, "prototyping": 7, "communication": 6, "empathy": 7, "creativity": 6, "visual_communication": 5},
        "salary": {"entry": "$60,000", "mid": "$100,000", "senior": "$150,000+"},
        "growth": ["Junior UX Designer", "UX Designer", "Senior UX Designer", "Lead Designer", "Head of Design"],
        "description": "Create intuitive, accessible, and delightful user experiences through research-driven design.",
        "typical_degree": "Bachelor's in Design/HCI/Psychology",
        "demand": "high",
        "personality": ["empathetic", "creative", "user-focused"],
        "roadmap": [
            {"month": 1, "title": "UX Foundations", "tasks": ["Design thinking workshop", "Heuristic evaluation", "User research basics"], "stack": "Figma, Miro, Notion", "concepts": "Design Thinking, Usability Heuristics"},
            {"month": 2, "title": "User Research", "tasks": ["Conduct interviews", "Usability testing", "Affinity mapping"], "stack": "Maze, Lookback, FigJam", "concepts": "Qualitative Research, Personas, Journey Maps"},
            {"month": 3, "title": "UI Design", "tasks": ["Design system creation", "Component library", "Responsive design"], "stack": "Figma, Adobe XD", "concepts": "Visual Hierarchy, Typography, Color Theory"},
            {"month": 4, "title": "Prototyping & Testing", "tasks": ["Interactive prototypes", "A/B design testing", "Accessibility audit"], "stack": "Figma, ProtoPie, WAVE", "concepts": "Interaction Design, A11y, Motion Design"},
            {"month": 5, "title": "Design Systems", "tasks": ["Token-based design", "Documentation", "Developer handoff"], "stack": "Figma, Storybook, Zeroheight", "concepts": "Atomic Design, Design Tokens"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Build case studies", "Portfolio website", "Design challenges"], "stack": "Portfolio Site, Dribbble, Behance", "concepts": "UX Case Studies, Design Interviews"},
        ],
    },
    "Data Analyst": {
        "skills": {"data_analysis": 9, "sql": 8, "visualization": 7, "statistics": 6, "communication": 6, "business_intelligence": 6, "excel": 5, "python": 5, "analytical_thinking": 7},
        "salary": {"entry": "$55,000", "mid": "$85,000", "senior": "$120,000+"},
        "growth": ["Junior Analyst", "Data Analyst", "Senior Analyst", "Analytics Manager", "Director of Analytics"],
        "description": "Transform raw data into actionable insights through analysis, visualization, and storytelling.",
        "typical_degree": "Bachelor's in Statistics/CS/Business",
        "demand": "high",
        "personality": ["analytical", "detail-oriented", "communicative"],
        "roadmap": [
            {"month": 1, "title": "SQL & Excel Mastery", "tasks": ["Advanced SQL queries", "Pivot tables & VLOOKUP", "Data cleaning"], "stack": "SQL, Excel, Google Sheets", "concepts": "Joins, Aggregations, Data Cleaning"},
            {"month": 2, "title": "Statistics & Analysis", "tasks": ["Descriptive statistics", "Hypothesis testing", "Correlation analysis"], "stack": "Python, Pandas, SciPy", "concepts": "Distributions, P-values, Confidence Intervals"},
            {"month": 3, "title": "Data Visualization", "tasks": ["Dashboard creation", "Interactive charts", "Storytelling with data"], "stack": "Tableau, Power BI, Matplotlib", "concepts": "Visual Encoding, Dashboard Design"},
            {"month": 4, "title": "Business Intelligence", "tasks": ["KPI definition", "Funnel analysis", "Cohort analysis"], "stack": "Looker, Metabase, dbt", "concepts": "Business Metrics, Data Modeling"},
            {"month": 5, "title": "Advanced Analytics", "tasks": ["Predictive modeling basics", "A/B testing", "Automation"], "stack": "Scikit-learn, Python, Airflow", "concepts": "Regression, Experimentation"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Analytics portfolio", "Case study presentations", "Interview prep"], "stack": "GitHub, Notion, Tableau Public", "concepts": "Business Cases, Analyst Interviews"},
        ],
    },
    "Cloud Solutions Architect": {
        "skills": {"cloud_computing": 9, "systems_thinking": 8, "infrastructure": 8, "devops": 7, "coding": 5, "security_engineering": 6, "networking": 6, "communication": 5, "problem_solving": 7},
        "salary": {"entry": "$85,000", "mid": "$145,000", "senior": "$200,000+"},
        "growth": ["Cloud Engineer", "Solutions Architect", "Senior Architect", "Principal Architect", "VP of Engineering"],
        "description": "Design secure, scalable, and cost-effective cloud architectures for enterprise systems.",
        "typical_degree": "Bachelor's in CS/IT + Cloud Certifications",
        "demand": "very_high",
        "personality": ["strategic", "systematic", "big-picture-thinker"],
        "roadmap": [
            {"month": 1, "title": "Cloud Fundamentals", "tasks": ["AWS/GCP core services", "Networking in cloud", "IAM & security"], "stack": "AWS, GCP, Azure", "concepts": "Regions, VPCs, IAM Policies"},
            {"month": 2, "title": "Compute & Storage", "tasks": ["EC2, Lambda, GKE", "S3, RDS, DynamoDB", "Cost optimization"], "stack": "EC2, Lambda, S3, RDS", "concepts": "Serverless, Object Storage, RDBMS"},
            {"month": 3, "title": "Architecture Patterns", "tasks": ["Multi-tier architecture", "Microservices on cloud", "Event-driven design"], "stack": "API Gateway, SQS, SNS", "concepts": "Well-Architected Framework, HA, DR"},
            {"month": 4, "title": "Infrastructure as Code", "tasks": ["Terraform modules", "CloudFormation", "Policy as Code"], "stack": "Terraform, CloudFormation, OPA", "concepts": "IaC, GitOps, Compliance"},
            {"month": 5, "title": "Security & Compliance", "tasks": ["Cloud security posture", "Encryption at rest/transit", "Compliance frameworks"], "stack": "AWS Config, GuardDuty, KMS", "concepts": "Zero Trust, SOC 2, GDPR"},
            {"month": 6, "title": "Certification & Career", "tasks": ["AWS SA Associate cert", "Architecture case studies", "Interview preparation"], "stack": "AWS Certification, Whitepapers", "concepts": "Architecture Reviews, Well-Architected"},
        ],
    },
    "Cybersecurity Analyst": {
        "skills": {"cybersecurity": 9, "networking": 8, "risk_assessment": 7, "analytical_thinking": 7, "ethical_hacking": 6, "problem_solving": 6, "systems_administration": 5, "communication": 5, "attention_to_detail": 6},
        "salary": {"entry": "$65,000", "mid": "$105,000", "senior": "$155,000+"},
        "growth": ["Junior Security Analyst", "Security Analyst", "Senior Analyst", "Security Architect", "CISO"],
        "description": "Protect organizations from cyber threats through monitoring, analysis, and incident response.",
        "typical_degree": "Bachelor's in CS/Cybersecurity + Certifications",
        "demand": "very_high",
        "personality": ["vigilant", "analytical", "detail-oriented"],
        "roadmap": [
            {"month": 1, "title": "Security Foundations", "tasks": ["Networking fundamentals", "Security concepts", "Linux security"], "stack": "Linux, Wireshark, Nmap", "concepts": "CIA Triad, OSI Model, Firewalls"},
            {"month": 2, "title": "Threat Detection", "tasks": ["SIEM setup", "Log analysis", "Intrusion detection"], "stack": "Splunk, ELK Stack, Snort", "concepts": "SIEM, IDS/IPS, Log Management"},
            {"month": 3, "title": "Vulnerability Assessment", "tasks": ["Vulnerability scanning", "Penetration testing basics", "Web app security"], "stack": "Nessus, Burp Suite, OWASP ZAP", "concepts": "OWASP Top 10, CVEs, Risk Scoring"},
            {"month": 4, "title": "Incident Response", "tasks": ["IR playbooks", "Forensic analysis", "Malware analysis basics"], "stack": "Autopsy, Volatility, YARA", "concepts": "IR Lifecycle, Chain of Custody"},
            {"month": 5, "title": "Governance & Compliance", "tasks": ["Policy development", "Risk assessment frameworks", "Compliance auditing"], "stack": "ISO 27001, NIST, SOC 2", "concepts": "Risk Management, Compliance, GRC"},
            {"month": 6, "title": "Certification & Career", "tasks": ["CompTIA Security+", "Build security lab", "Interview prep"], "stack": "CompTIA, TryHackMe, HackTheBox", "concepts": "Security Certifications, Blue Team"},
        ],
    },
    "AI Research Scientist": {
        "skills": {"machine_learning": 9, "deep_learning": 9, "mathematics": 9, "research": 8, "python": 7, "critical_thinking": 7, "writing": 6, "statistics": 7, "analytical_thinking": 8},
        "salary": {"entry": "$90,000", "mid": "$160,000", "senior": "$250,000+"},
        "growth": ["Research Intern", "Research Scientist", "Senior Scientist", "Principal Scientist", "Research Director"],
        "description": "Advance the field of AI through novel research, experimentation, and publications.",
        "typical_degree": "PhD in CS/AI/ML/Mathematics",
        "demand": "high",
        "personality": ["curious", "rigorous", "creative"],
        "roadmap": [
            {"month": 1, "title": "Mathematical Foundations", "tasks": ["Linear algebra deep dive", "Probability theory", "Optimization methods"], "stack": "MATLAB, Python, LaTeX", "concepts": "Matrix Calculus, Bayesian Inference"},
            {"month": 2, "title": "Core ML Theory", "tasks": ["Statistical learning theory", "Kernel methods", "Graphical models"], "stack": "Python, R, Jupyter", "concepts": "PAC Learning, VC Dimension, MRFs"},
            {"month": 3, "title": "Deep Learning Research", "tasks": ["Reproduce 3 papers", "Implement novel architectures", "Ablation studies"], "stack": "PyTorch, JAX, Weights & Biases", "concepts": "Transformers, GANs, Diffusion Models"},
            {"month": 4, "title": "Specialization", "tasks": ["Choose research area", "Literature review", "Formulate hypothesis"], "stack": "arXiv, Google Scholar, Overleaf", "concepts": "Research Methodology, Paper Writing"},
            {"month": 5, "title": "Experimentation", "tasks": ["Design experiments", "Run large-scale training", "Analyze results"], "stack": "GPUs, SLURM, MLflow", "concepts": "Experiment Design, Compute Management"},
            {"month": 6, "title": "Publication & Career", "tasks": ["Write research paper", "Submit to conference", "Build research portfolio"], "stack": "LaTeX, Overleaf, OpenReview", "concepts": "Peer Review, Conference Presentations"},
        ],
    },
    "Mobile App Developer": {
        "skills": {"mobile_development": 9, "coding": 8, "ui_design": 6, "problem_solving": 7, "debugging": 6, "api_design": 5, "design_thinking": 4, "communication": 4},
        "salary": {"entry": "$65,000", "mid": "$110,000", "senior": "$165,000+"},
        "growth": ["Junior Mobile Dev", "Mobile Developer", "Senior Mobile Dev", "Mobile Architect", "Engineering Manager"],
        "description": "Build native and cross-platform mobile applications for iOS and Android.",
        "typical_degree": "Bachelor's in CS/IT",
        "demand": "high",
        "personality": ["creative", "user-focused", "detail-oriented"],
        "roadmap": [
            {"month": 1, "title": "Mobile Fundamentals", "tasks": ["React Native / Flutter basics", "Component architecture", "Navigation patterns"], "stack": "React Native, Flutter, Dart", "concepts": "Mobile UI Patterns, Navigation"},
            {"month": 2, "title": "State & Data", "tasks": ["State management", "API integration", "Local storage"], "stack": "Redux, REST APIs, AsyncStorage", "concepts": "State Patterns, Offline-first"},
            {"month": 3, "title": "Native Features", "tasks": ["Camera & GPS", "Push notifications", "Biometric auth"], "stack": "Expo, Firebase, OneSignal", "concepts": "Native Modules, Permissions"},
            {"month": 4, "title": "Performance & Testing", "tasks": ["Performance profiling", "Unit/integration tests", "UI testing"], "stack": "Flipper, Jest, Detox", "concepts": "Memory Leaks, Frame Drops, Testing"},
            {"month": 5, "title": "App Store Launch", "tasks": ["App store optimization", "Beta testing", "Release management"], "stack": "App Store Connect, Google Play Console", "concepts": "ASO, CI/CD for Mobile"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Publish 2 apps", "Open source contribution", "Interview prep"], "stack": "GitHub, Portfolio, LeetCode", "concepts": "Mobile System Design, Interviews"},
        ],
    },
    "Business Analyst": {
        "skills": {"analytical_thinking": 8, "communication": 8, "business_acumen": 7, "data_analysis": 6, "strategic_thinking": 6, "problem_solving": 6, "sql": 5, "visualization": 5, "documentation": 6},
        "salary": {"entry": "$55,000", "mid": "$85,000", "senior": "$125,000+"},
        "growth": ["Junior BA", "Business Analyst", "Senior BA", "Lead BA", "Director of Business Analysis"],
        "description": "Bridge business needs and technology solutions through requirements analysis and process improvement.",
        "typical_degree": "Bachelor's in Business/CS/Engineering",
        "demand": "high",
        "personality": ["analytical", "communicative", "bridge-builder"],
        "roadmap": [
            {"month": 1, "title": "BA Foundations", "tasks": ["Requirements gathering techniques", "Stakeholder mapping", "Business process modeling"], "stack": "Visio, Miro, Confluence", "concepts": "BPMN, Use Cases, User Stories"},
            {"month": 2, "title": "Data & Analysis", "tasks": ["SQL for business queries", "Excel advanced analysis", "Data-driven insights"], "stack": "SQL, Excel, Power BI", "concepts": "KPIs, Root Cause Analysis"},
            {"month": 3, "title": "Agile & Scrum", "tasks": ["Sprint planning", "Backlog grooming", "Acceptance criteria writing"], "stack": "Jira, Confluence, Trello", "concepts": "Agile, Scrum, Kanban"},
            {"month": 4, "title": "Process Optimization", "tasks": ["Gap analysis", "Process re-engineering", "Cost-benefit analysis"], "stack": "Lucidchart, Lean Six Sigma", "concepts": "Value Stream Mapping, ROI Analysis"},
            {"month": 5, "title": "Technical Communication", "tasks": ["BRD/FRD writing", "Presentation skills", "Stakeholder management"], "stack": "PowerPoint, Word, Loom", "concepts": "Requirements Specs, Executive Summaries"},
            {"month": 6, "title": "Certification & Career", "tasks": ["CBAP preparation", "Case study portfolio", "Interview preparation"], "stack": "IIBA, LinkedIn, Notion", "concepts": "BA Certifications, Case Interviews"},
        ],
    },
    "Project Manager": {
        "skills": {"project_management": 9, "communication": 8, "leadership": 7, "planning": 7, "team_management": 6, "problem_solving": 6, "agile_methodology": 6, "risk_assessment": 5, "strategic_thinking": 5},
        "salary": {"entry": "$60,000", "mid": "$95,000", "senior": "$140,000+"},
        "growth": ["Project Coordinator", "Project Manager", "Senior PM", "Program Manager", "VP of Operations"],
        "description": "Lead cross-functional teams to deliver projects on time, within scope, and on budget.",
        "typical_degree": "Bachelor's in Business/Engineering + PMP",
        "demand": "high",
        "personality": ["organized", "communicative", "decisive"],
        "roadmap": [
            {"month": 1, "title": "PM Fundamentals", "tasks": ["Project lifecycle", "Scope management", "WBS creation"], "stack": "MS Project, Asana, Trello", "concepts": "PMBOK, Project Charter, Scope Statement"},
            {"month": 2, "title": "Agile & Scrum", "tasks": ["Scrum master role", "Sprint ceremonies", "Velocity tracking"], "stack": "Jira, Confluence", "concepts": "Scrum, Kanban, SAFe"},
            {"month": 3, "title": "Risk & Budget", "tasks": ["Risk register", "Budget forecasting", "Earned value management"], "stack": "Excel, Smartsheet", "concepts": "Risk Matrix, EVM, Cost Baseline"},
            {"month": 4, "title": "Stakeholder Management", "tasks": ["Communication plan", "RACI matrix", "Status reporting"], "stack": "PowerPoint, Slack, Loom", "concepts": "Stakeholder Analysis, RACI, Dashboards"},
            {"month": 5, "title": "Leadership & Team", "tasks": ["Conflict resolution", "Team motivation", "Performance tracking"], "stack": "15Five, Lattice", "concepts": "Servant Leadership, Tuckman's Stages"},
            {"month": 6, "title": "Certification & Career", "tasks": ["PMP preparation", "Case study portfolio", "Interview prep"], "stack": "PMI, Udemy, LinkedIn", "concepts": "PMP, PRINCE2, Agile Certifications"},
        ],
    },
    "Blockchain Developer": {
        "skills": {"coding": 8, "systems_thinking": 7, "cryptography": 7, "problem_solving": 7, "mathematics": 5, "database": 5, "security_engineering": 5},
        "salary": {"entry": "$75,000", "mid": "$130,000", "senior": "$190,000+"},
        "growth": ["Junior Blockchain Dev", "Blockchain Developer", "Senior Blockchain Dev", "Blockchain Architect", "Web3 Lead"],
        "description": "Build decentralized applications, smart contracts, and blockchain infrastructure.",
        "typical_degree": "Bachelor's in CS/Mathematics",
        "demand": "medium",
        "personality": ["innovative", "security-minded", "technically deep"],
        "roadmap": [
            {"month": 1, "title": "Blockchain Fundamentals", "tasks": ["Blockchain concepts", "Consensus mechanisms", "Cryptographic primitives"], "stack": "Bitcoin, Ethereum whitepaper", "concepts": "Hashing, Merkle Trees, PoW/PoS"},
            {"month": 2, "title": "Smart Contracts", "tasks": ["Solidity programming", "ERC standards", "Contract testing"], "stack": "Solidity, Hardhat, Remix", "concepts": "Gas Optimization, ERC-20, ERC-721"},
            {"month": 3, "title": "DApp Development", "tasks": ["Frontend integration", "Wallet connection", "IPFS storage"], "stack": "ethers.js, MetaMask, IPFS", "concepts": "Web3 Stack, Decentralized Storage"},
            {"month": 4, "title": "DeFi & Protocols", "tasks": ["AMM mechanisms", "Lending protocols", "Yield strategies"], "stack": "Uniswap, Aave, Chainlink", "concepts": "DeFi Primitives, Oracles, Flash Loans"},
            {"month": 5, "title": "Security & Auditing", "tasks": ["Common vulnerabilities", "Smart contract auditing", "Formal verification"], "stack": "Slither, MythX, Echidna", "concepts": "Reentrancy, Front-running, Audit Reports"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Build DeFi project", "Contribute to protocol", "Interview prep"], "stack": "GitHub, Etherscan, LeetCode", "concepts": "Web3 Interviews, Protocol Design"},
        ],
    },
    "Robotics Engineer": {
        "skills": {"robotics": 9, "embedded_systems": 8, "coding": 7, "mathematics": 7, "electronics": 6, "problem_solving": 7, "systems_thinking": 6, "cad_design": 5, "physics": 6},
        "salary": {"entry": "$70,000", "mid": "$115,000", "senior": "$165,000+"},
        "growth": ["Junior Robotics Engineer", "Robotics Engineer", "Senior Robotics Eng", "Lead Robotics Eng", "Robotics Architect"],
        "description": "Design, program, and deploy intelligent robotic systems for industrial and consumer applications.",
        "typical_degree": "Bachelor's/Master's in Robotics/ECE/Mechanical",
        "demand": "high",
        "personality": ["hands-on", "systematic", "innovative"],
        "roadmap": [
            {"month": 1, "title": "Robotics Foundations", "tasks": ["Kinematics & dynamics", "ROS basics", "Sensor integration"], "stack": "ROS, Python, Arduino", "concepts": "Forward/Inverse Kinematics, TF Trees"},
            {"month": 2, "title": "Embedded Programming", "tasks": ["Microcontroller programming", "Real-time systems", "Motor control"], "stack": "C/C++, STM32, PID Controllers", "concepts": "RTOS, PWM, Serial Communication"},
            {"month": 3, "title": "Perception", "tasks": ["Computer vision for robots", "SLAM implementation", "Sensor fusion"], "stack": "OpenCV, ORB-SLAM, Kalman Filter", "concepts": "Feature Detection, Localization, Mapping"},
            {"month": 4, "title": "Motion Planning", "tasks": ["Path planning algorithms", "Obstacle avoidance", "Manipulation planning"], "stack": "MoveIt, RRT, A*", "concepts": "Configuration Space, Trajectory Optimization"},
            {"month": 5, "title": "ML for Robotics", "tasks": ["Reinforcement learning", "Sim-to-real transfer", "Imitation learning"], "stack": "PyTorch, Isaac Sim, Gym", "concepts": "RL, Domain Randomization, Reward Shaping"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Build autonomous robot", "Document projects", "Interview prep"], "stack": "GitHub, YouTube, ROS Wiki", "concepts": "Robotics System Design, Demos"},
        ],
    },
    "IoT Engineer": {
        "skills": {"iot": 9, "embedded_systems": 8, "cloud_computing": 6, "coding": 6, "networking": 6, "systems_thinking": 6, "electronics": 5, "problem_solving": 6},
        "salary": {"entry": "$65,000", "mid": "$105,000", "senior": "$150,000+"},
        "growth": ["Junior IoT Developer", "IoT Engineer", "Senior IoT Eng", "IoT Architect", "Head of IoT"],
        "description": "Connect physical devices to cloud platforms for smart monitoring and automation.",
        "typical_degree": "Bachelor's in ECE/CS/IT",
        "demand": "high",
        "personality": ["hands-on", "systematic", "innovative"],
        "roadmap": [
            {"month": 1, "title": "IoT Foundations", "tasks": ["Microcontroller basics", "Sensor interfacing", "Communication protocols"], "stack": "Arduino, ESP32, MQTT", "concepts": "I2C, SPI, UART, MQTT"},
            {"month": 2, "title": "Connectivity", "tasks": ["WiFi/BLE integration", "LoRaWAN setup", "Edge computing"], "stack": "ESP32, Raspberry Pi, Node-RED", "concepts": "Edge vs Cloud, Protocol Selection"},
            {"month": 3, "title": "Cloud Integration", "tasks": ["IoT cloud platforms", "Data ingestion pipelines", "Device management"], "stack": "AWS IoT Core, Azure IoT Hub", "concepts": "Device Shadow, Telemetry, OTA Updates"},
            {"month": 4, "title": "Data & Analytics", "tasks": ["Time-series databases", "Real-time dashboards", "Anomaly detection"], "stack": "InfluxDB, Grafana, Python", "concepts": "TSDB, Stream Processing, Alerting"},
            {"month": 5, "title": "Security & Scale", "tasks": ["Device authentication", "Secure boot", "Fleet management"], "stack": "TLS, X.509, AWS IoT Greengrass", "concepts": "IoT Security, Zero Trust, OTA"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["End-to-end IoT project", "Documentation", "Interview prep"], "stack": "GitHub, Hackster.io", "concepts": "IoT Architecture, System Design"},
        ],
    },
    "Mechanical Engineer": {
        "skills": {"mechanical_engineering": 9, "cad_design": 8, "mathematics": 7, "physics": 7, "manufacturing": 6, "problem_solving": 7, "attention_to_detail": 6, "3d_modeling": 5},
        "salary": {"entry": "$60,000", "mid": "$90,000", "senior": "$130,000+"},
        "growth": ["Junior Mechanical Eng", "Mechanical Engineer", "Senior Mechanical Eng", "Lead Engineer", "Engineering Manager"],
        "description": "Design, analyze, and manufacture mechanical systems from concept to production.",
        "typical_degree": "Bachelor's in Mechanical Engineering",
        "demand": "medium",
        "personality": ["detail-oriented", "practical", "analytical"],
        "roadmap": [
            {"month": 1, "title": "CAD & Design", "tasks": ["SolidWorks mastery", "Assembly modeling", "Engineering drawings"], "stack": "SolidWorks, AutoCAD", "concepts": "GD&T, Tolerance Analysis"},
            {"month": 2, "title": "FEA & Simulation", "tasks": ["Stress analysis", "Thermal simulation", "CFD basics"], "stack": "ANSYS, COMSOL", "concepts": "FEA, Meshing, Boundary Conditions"},
            {"month": 3, "title": "Manufacturing", "tasks": ["CNC programming", "3D printing", "Material selection"], "stack": "G-code, Ultimaker, MatWeb", "concepts": "DFM, Additive vs Subtractive"},
            {"month": 4, "title": "Thermodynamics & Fluids", "tasks": ["HVAC design", "Fluid dynamics problems", "Heat exchanger design"], "stack": "EES, MATLAB", "concepts": "Heat Transfer, Fluid Mechanics"},
            {"month": 5, "title": "Project & Quality", "tasks": ["Design reviews", "FMEA", "Quality control"], "stack": "Minitab, Excel", "concepts": "Six Sigma, DFMEA, GD&T"},
            {"month": 6, "title": "FE Exam & Career", "tasks": ["FE exam preparation", "Portfolio creation", "Interview prep"], "stack": "NCEES, LinkedIn", "concepts": "PE Licensure, Engineering Ethics"},
        ],
    },
    "Civil Engineer": {
        "skills": {"civil_engineering": 9, "drafting": 7, "mathematics": 7, "project_management": 6, "spatial_reasoning": 6, "attention_to_detail": 6, "problem_solving": 6, "cad_design": 6},
        "salary": {"entry": "$58,000", "mid": "$85,000", "senior": "$125,000+"},
        "growth": ["Junior Civil Engineer", "Civil Engineer", "Senior Civil Eng", "Project Engineer", "Engineering Manager"],
        "description": "Design and oversee construction of infrastructure including buildings, roads, and bridges.",
        "typical_degree": "Bachelor's in Civil Engineering",
        "demand": "medium",
        "personality": ["practical", "detail-oriented", "safety-conscious"],
        "roadmap": [
            {"month": 1, "title": "Structural Analysis", "tasks": ["Load calculations", "Beam/column design", "Structural software"], "stack": "STAAD Pro, ETABS, AutoCAD", "concepts": "Statics, Strength of Materials"},
            {"month": 2, "title": "CAD & BIM", "tasks": ["AutoCAD 2D/3D", "Revit BIM modeling", "Site plans"], "stack": "AutoCAD, Revit, Civil 3D", "concepts": "BIM, Coordinate Systems, GIS"},
            {"month": 3, "title": "Geotechnical", "tasks": ["Soil testing", "Foundation design", "Slope stability"], "stack": "Plaxis, GeoStudio", "concepts": "Soil Mechanics, Bearing Capacity"},
            {"month": 4, "title": "Transportation", "tasks": ["Road design", "Traffic analysis", "Pavement design"], "stack": "Civil 3D, PTV Vissim", "concepts": "Highway Design, Level of Service"},
            {"month": 5, "title": "Construction Mgmt", "tasks": ["Scheduling (CPM)", "Cost estimation", "Safety planning"], "stack": "Primavera, MS Project, Excel", "concepts": "CPM, Earned Value, OSHA Safety"},
            {"month": 6, "title": "FE Exam & Career", "tasks": ["FE exam preparation", "Portfolio", "Interview prep"], "stack": "NCEES, LinkedIn", "concepts": "PE Licensure, Professional Development"},
        ],
    },
    "Consultant": {
        "skills": {"analytical_thinking": 9, "communication": 8, "strategic_thinking": 8, "problem_solving": 8, "business_acumen": 7, "data_analysis": 5, "leadership": 5, "presentation": 7},
        "salary": {"entry": "$70,000", "mid": "$120,000", "senior": "$200,000+"},
        "growth": ["Analyst", "Consultant", "Senior Consultant", "Manager", "Partner"],
        "description": "Solve complex business problems and drive organizational transformation for clients.",
        "typical_degree": "MBA / Bachelor's in Business/Engineering",
        "demand": "high",
        "personality": ["analytical", "persuasive", "adaptable"],
        "roadmap": [
            {"month": 1, "title": "Consulting Frameworks", "tasks": ["Case interview frameworks", "Hypothesis-driven thinking", "MECE structuring"], "stack": "PowerPoint, Excel", "concepts": "MECE, Issue Trees, 80/20 Rule"},
            {"month": 2, "title": "Data Analysis", "tasks": ["Excel financial modeling", "Data-driven insights", "Benchmarking"], "stack": "Excel, Tableau, SQL", "concepts": "Financial Statements, Market Sizing"},
            {"month": 3, "title": "Communication", "tasks": ["Slide writing", "Executive summaries", "Client presentations"], "stack": "PowerPoint, Minto Pyramid", "concepts": "Pyramid Principle, Storyboarding"},
            {"month": 4, "title": "Industry Knowledge", "tasks": ["Industry deep dives", "Competitive analysis", "Market trends"], "stack": "Capital IQ, McKinsey Insights", "concepts": "Porter's Five Forces, SWOT, PESTEL"},
            {"month": 5, "title": "Client Management", "tasks": ["Stakeholder mapping", "Workshop facilitation", "Change management"], "stack": "Miro, Zoom, Confluence", "concepts": "ADKAR, Stakeholder Analysis"},
            {"month": 6, "title": "Case Prep & Career", "tasks": ["50+ case interviews", "Behavioral stories", "Networking"], "stack": "CaseCoach, Victor Cheng", "concepts": "Case Interviews, Fit Interviews"},
        ],
    },
    "Technical Writer": {
        "skills": {"writing": 9, "communication": 8, "research": 7, "documentation": 8, "attention_to_detail": 7, "critical_thinking": 5, "coding": 3},
        "salary": {"entry": "$50,000", "mid": "$80,000", "senior": "$115,000+"},
        "growth": ["Junior Writer", "Technical Writer", "Senior Writer", "Lead Writer", "Documentation Manager"],
        "description": "Create clear, accurate technical documentation, guides, and API references.",
        "typical_degree": "Bachelor's in English/CS/Communications",
        "demand": "medium",
        "personality": ["detail-oriented", "clear communicator", "patient"],
        "roadmap": [
            {"month": 1, "title": "Writing Foundations", "tasks": ["Technical writing style", "Documentation standards", "Markdown/RST"], "stack": "Markdown, Git, VS Code", "concepts": "Style Guides, Information Architecture"},
            {"month": 2, "title": "Tools & Platforms", "tasks": ["Docs-as-code", "API documentation", "Static site generators"], "stack": "Docusaurus, Swagger, ReadTheDocs", "concepts": "API Docs, OpenAPI Spec"},
            {"month": 3, "title": "Developer Docs", "tasks": ["SDK documentation", "Tutorials & quickstarts", "Code samples"], "stack": "GitHub, MDX, Jupyter", "concepts": "Developer Experience, Code Examples"},
            {"month": 4, "title": "Visual Communication", "tasks": ["Diagrams & flowcharts", "Screenshots & videos", "Infographics"], "stack": "Mermaid, Loom, Canva", "concepts": "Visual Hierarchy, Diagram Types"},
            {"month": 5, "title": "Content Strategy", "tasks": ["Content audit", "SEO for docs", "Analytics"], "stack": "Google Analytics, Algolia", "concepts": "Content Lifecycle, Search Optimization"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Documentation portfolio", "Writing samples", "Interview prep"], "stack": "Portfolio Site, GitHub", "concepts": "Writing Tests, Portfolio Reviews"},
        ],
    },
    "QA/Test Engineer": {
        "skills": {"testing": 9, "quality_assurance": 8, "debugging": 7, "automation": 6, "coding": 5, "attention_to_detail": 8, "analytical_thinking": 6, "communication": 5, "problem_solving": 6},
        "salary": {"entry": "$55,000", "mid": "$90,000", "senior": "$130,000+"},
        "growth": ["Junior QA", "QA Engineer", "Senior QA", "QA Lead", "QA Manager"],
        "description": "Ensure software quality through systematic testing, automation, and defect management.",
        "typical_degree": "Bachelor's in CS/IT",
        "demand": "high",
        "personality": ["meticulous", "systematic", "quality-focused"],
        "roadmap": [
            {"month": 1, "title": "QA Foundations", "tasks": ["Testing fundamentals", "Test case design", "Bug reporting"], "stack": "Jira, TestRail, Excel", "concepts": "SDLC, Test Types, Severity vs Priority"},
            {"month": 2, "title": "Manual Testing", "tasks": ["Functional testing", "Regression testing", "Exploratory testing"], "stack": "Browser DevTools, Postman", "concepts": "Black/White Box, Boundary Value Analysis"},
            {"month": 3, "title": "Automation", "tasks": ["Selenium/Cypress setup", "Page object model", "Data-driven testing"], "stack": "Selenium, Cypress, Python", "concepts": "Test Automation Framework, POM"},
            {"month": 4, "title": "API Testing", "tasks": ["REST API testing", "Contract testing", "Performance testing"], "stack": "Postman, Rest Assured, k6", "concepts": "API Validation, Load Testing, SLAs"},
            {"month": 5, "title": "CI/CD Integration", "tasks": ["Tests in pipeline", "Reporting", "Test environment mgmt"], "stack": "GitHub Actions, Docker, Allure", "concepts": "Shift-Left Testing, Test Pyramid"},
            {"month": 6, "title": "Certification & Career", "tasks": ["ISTQB preparation", "Automation portfolio", "Interview prep"], "stack": "ISTQB, GitHub, LeetCode", "concepts": "QA Interviews, Automation Strategy"},
        ],
    },
    "Healthcare Data Analyst": {
        "skills": {"data_analysis": 8, "medical_knowledge": 6, "statistics": 7, "sql": 7, "communication": 6, "analytical_thinking": 7, "attention_to_detail": 7, "visualization": 5, "empathy": 4},
        "salary": {"entry": "$55,000", "mid": "$85,000", "senior": "$120,000+"},
        "growth": ["Junior Analyst", "Healthcare Data Analyst", "Senior Analyst", "Analytics Manager", "Director"],
        "description": "Analyze clinical and operational healthcare data to improve patient outcomes and efficiency.",
        "typical_degree": "Bachelor's in Health Informatics/Statistics/Public Health",
        "demand": "high",
        "personality": ["analytical", "empathetic", "detail-oriented"],
        "roadmap": [
            {"month": 1, "title": "Healthcare Data Basics", "tasks": ["Health data standards", "EHR systems", "Clinical terminology"], "stack": "SQL, Excel", "concepts": "HL7, FHIR, ICD-10, CPT Codes"},
            {"month": 2, "title": "Data Analysis", "tasks": ["Patient cohort analysis", "Clinical outcomes tracking", "Quality metrics"], "stack": "Python, Pandas, SQL", "concepts": "Population Health, Quality Measures"},
            {"month": 3, "title": "Visualization & Reporting", "tasks": ["Healthcare dashboards", "Regulatory reporting", "Data storytelling"], "stack": "Tableau, Power BI, Excel", "concepts": "Dashboard Design, CMS Reporting"},
            {"month": 4, "title": "Statistics for Healthcare", "tasks": ["Clinical trial analysis", "Survival analysis", "Epidemiology basics"], "stack": "R, SAS, Python", "concepts": "Kaplan-Meier, Cox Regression, RCTs"},
            {"month": 5, "title": "Compliance & Privacy", "tasks": ["HIPAA compliance", "Data de-identification", "Audit trails"], "stack": "De-ID tools, Audit systems", "concepts": "HIPAA, PHI, Data Governance"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Healthcare analytics project", "Certifications", "Interview prep"], "stack": "Portfolio, AHIMA, LinkedIn", "concepts": "Health Informatics Certifications"},
        ],
    },
    "Biomedical Engineer": {
        "skills": {"research": 7, "problem_solving": 7, "mathematics": 6, "coding": 4, "medical_knowledge": 5, "data_analysis": 5, "attention_to_detail": 6, "chemistry": 4, "electronics": 4},
        "salary": {"entry": "$60,000", "mid": "$90,000", "senior": "$130,000+"},
        "growth": ["Junior BME", "Biomedical Engineer", "Senior BME", "Principal Engineer", "R&D Director"],
        "description": "Apply engineering principles to healthcare: design medical devices, prosthetics, and diagnostic equipment.",
        "typical_degree": "Bachelor's/Master's in Biomedical Engineering",
        "demand": "medium",
        "personality": ["innovative", "detail-oriented", "mission-driven"],
        "roadmap": [
            {"month": 1, "title": "BME Foundations", "tasks": ["Biomechanics basics", "Biocompatibility", "Medical device regulations"], "stack": "MATLAB, SolidWorks", "concepts": "FDA 510(k), ISO 13485, Biomaterials"},
            {"month": 2, "title": "Signal Processing", "tasks": ["Biosignal analysis", "ECG/EEG processing", "Filtering techniques"], "stack": "MATLAB, Python, LabVIEW", "concepts": "DSP, Fourier Transform, Filtering"},
            {"month": 3, "title": "Medical Imaging", "tasks": ["Image processing", "DICOM standards", "Segmentation"], "stack": "Python, ITK, 3D Slicer", "concepts": "CT, MRI, Ultrasound Physics"},
            {"month": 4, "title": "Device Design", "tasks": ["Prosthetics design", "Prototype fabrication", "Testing protocols"], "stack": "SolidWorks, 3D Printing, Arduino", "concepts": "DFM, Human Factors, Verification"},
            {"month": 5, "title": "Regulatory & Quality", "tasks": ["Design controls", "Risk management", "Clinical evaluation"], "stack": "ISO 14971, IEC 62304", "concepts": "V-Model, FMEA, DHF/DMR"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Capstone project", "Research publication", "Interview prep"], "stack": "GitHub, ResearchGate, LinkedIn", "concepts": "BME Interviews, R&D Portfolios"},
        ],
    },
    "Game Developer": {
        "skills": {"coding": 8, "creativity": 7, "problem_solving": 7, "3d_modeling": 5, "mathematics": 5, "debugging": 6, "design_thinking": 5, "physics": 4},
        "salary": {"entry": "$55,000", "mid": "$95,000", "senior": "$140,000+"},
        "growth": ["Junior Game Dev", "Game Developer", "Senior Game Dev", "Lead Developer", "Technical Director"],
        "description": "Create interactive gaming experiences across platforms using game engines and programming.",
        "typical_degree": "Bachelor's in CS/Game Design",
        "demand": "medium",
        "personality": ["creative", "passionate", "detail-oriented"],
        "roadmap": [
            {"month": 1, "title": "Game Engine Basics", "tasks": ["Unity/Unreal fundamentals", "Scene management", "Input handling"], "stack": "Unity, C#, Unreal, C++", "concepts": "Game Loop, Component Architecture"},
            {"month": 2, "title": "Game Programming", "tasks": ["Physics systems", "AI behaviors", "Procedural generation"], "stack": "Unity, C#", "concepts": "Collision, Pathfinding, State Machines"},
            {"month": 3, "title": "Graphics & Shaders", "tasks": ["Shader programming", "Lighting", "Particle systems"], "stack": "HLSL/GLSL, Shader Graph", "concepts": "Rendering Pipeline, PBR, Post-processing"},
            {"month": 4, "title": "Multiplayer & Networking", "tasks": ["Client-server architecture", "Netcode", "Matchmaking"], "stack": "Mirror, Photon, Netcode", "concepts": "Lag Compensation, State Sync, Lobbies"},
            {"month": 5, "title": "Polish & Optimization", "tasks": ["Performance profiling", "Memory management", "Platform optimization"], "stack": "Unity Profiler, Frame Debugger", "concepts": "Draw Calls, LOD, Object Pooling"},
            {"month": 6, "title": "Portfolio & Launch", "tasks": ["Publish to Steam/itch.io", "Game jam participation", "Portfolio"], "stack": "Steam, itch.io, GitHub", "concepts": "Game Design Document, Playtesting"},
        ],
    },
    "Marketing Analyst": {
        "skills": {"marketing": 8, "data_analysis": 7, "analytical_thinking": 7, "communication": 7, "visualization": 5, "creativity": 5, "business_acumen": 5, "sql": 4},
        "salary": {"entry": "$50,000", "mid": "$80,000", "senior": "$120,000+"},
        "growth": ["Junior Analyst", "Marketing Analyst", "Senior Analyst", "Marketing Manager", "CMO"],
        "description": "Drive data-informed marketing strategies through campaign analysis and customer insights.",
        "typical_degree": "Bachelor's in Marketing/Business/Statistics",
        "demand": "high",
        "personality": ["analytical", "creative", "data-driven"],
        "roadmap": [
            {"month": 1, "title": "Marketing Foundations", "tasks": ["Digital marketing channels", "Customer segmentation", "Marketing funnel"], "stack": "Google Analytics, HubSpot", "concepts": "AIDA, Customer Journey, Attribution"},
            {"month": 2, "title": "Analytics Tools", "tasks": ["GA4 mastery", "UTM tracking", "Dashboard creation"], "stack": "GA4, Looker Studio, Excel", "concepts": "Web Analytics, Conversion Tracking"},
            {"month": 3, "title": "Campaign Analysis", "tasks": ["A/B testing", "ROI calculation", "Channel attribution"], "stack": "Google Ads, Meta Ads, SQL", "concepts": "CAC, LTV, ROAS, Attribution Models"},
            {"month": 4, "title": "Customer Analytics", "tasks": ["Cohort analysis", "Churn prediction", "RFM segmentation"], "stack": "Python, SQL, Mixpanel", "concepts": "CLV, Retention Curves, Segmentation"},
            {"month": 5, "title": "Advanced Analytics", "tasks": ["Marketing mix modeling", "Predictive analytics", "Sentiment analysis"], "stack": "Python, R, NLP libraries", "concepts": "MMM, Propensity Scoring, NLP"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Marketing analytics portfolio", "Case studies", "Interview prep"], "stack": "Portfolio Site, LinkedIn", "concepts": "Marketing Interviews, Case Studies"},
        ],
    },
    "Financial Analyst": {
        "skills": {"financial_analysis": 9, "analytical_thinking": 8, "mathematics": 7, "business_acumen": 7, "communication": 6, "data_analysis": 5, "excel": 7, "reporting": 5},
        "salary": {"entry": "$60,000", "mid": "$95,000", "senior": "$145,000+"},
        "growth": ["Junior Analyst", "Financial Analyst", "Senior Analyst", "Finance Manager", "CFO"],
        "description": "Analyze financial data, build models, and provide insights for business decision-making.",
        "typical_degree": "Bachelor's in Finance/Accounting/Economics",
        "demand": "high",
        "personality": ["analytical", "detail-oriented", "numbers-driven"],
        "roadmap": [
            {"month": 1, "title": "Financial Fundamentals", "tasks": ["Financial statements analysis", "Accounting basics", "Excel modeling"], "stack": "Excel, Google Sheets", "concepts": "P&L, Balance Sheet, Cash Flow"},
            {"month": 2, "title": "Financial Modeling", "tasks": ["DCF models", "Comparable analysis", "LBO basics"], "stack": "Excel, VBA", "concepts": "Valuation, WACC, Terminal Value"},
            {"month": 3, "title": "Data Analysis", "tasks": ["Financial data visualization", "KPI dashboards", "Variance analysis"], "stack": "Power BI, Tableau, SQL", "concepts": "Financial KPIs, Trend Analysis"},
            {"month": 4, "title": "Budgeting & Forecasting", "tasks": ["Budget planning", "Revenue forecasting", "Scenario analysis"], "stack": "Excel, Adaptive Planning", "concepts": "Rolling Forecasts, Sensitivity Analysis"},
            {"month": 5, "title": "Industry Specialization", "tasks": ["Sector analysis", "Competitor benchmarking", "Investment thesis"], "stack": "Bloomberg, Capital IQ, Excel", "concepts": "Industry Analysis, Market Research"},
            {"month": 6, "title": "Certification & Career", "tasks": ["CFA Level 1 prep", "Financial modeling portfolio", "Interview prep"], "stack": "CFA Institute, Wall Street Prep", "concepts": "CFA, Financial Interviews"},
        ],
    },
    "Content Creator / Digital Marketing": {
        "skills": {"creativity": 8, "communication": 8, "marketing": 7, "writing": 7, "visual_communication": 6, "design_thinking": 5, "analytical_thinking": 4, "storytelling": 7},
        "salary": {"entry": "$40,000", "mid": "$70,000", "senior": "$110,000+"},
        "growth": ["Content Creator", "Content Strategist", "Senior Strategist", "Head of Content", "Creative Director"],
        "description": "Create compelling digital content and develop strategies across social platforms.",
        "typical_degree": "Bachelor's in Communications/Marketing/Design",
        "demand": "high",
        "personality": ["creative", "trend-savvy", "storyteller"],
        "roadmap": [
            {"month": 1, "title": "Content Foundations", "tasks": ["Content strategy basics", "Platform analysis", "Brand voice development"], "stack": "Canva, Notion, Buffer", "concepts": "Content Pillars, Brand Identity"},
            {"month": 2, "title": "Visual Content", "tasks": ["Graphic design", "Video editing", "Photography basics"], "stack": "Canva, CapCut, Adobe Suite", "concepts": "Visual Hierarchy, Video Storytelling"},
            {"month": 3, "title": "Social Media", "tasks": ["Platform strategies", "Community building", "Engagement tactics"], "stack": "Instagram, YouTube, LinkedIn", "concepts": "Algorithm Understanding, Hashtag Strategy"},
            {"month": 4, "title": "SEO & Copywriting", "tasks": ["SEO writing", "Email marketing", "Landing page copy"], "stack": "Ahrefs, Mailchimp, WordPress", "concepts": "Keyword Research, CTR Optimization"},
            {"month": 5, "title": "Analytics & Growth", "tasks": ["Performance tracking", "A/B testing content", "Growth strategies"], "stack": "Google Analytics, Hootsuite", "concepts": "Engagement Metrics, Growth Hacking"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Content portfolio", "Case studies", "Personal brand"], "stack": "Portfolio Site, LinkedIn", "concepts": "Personal Branding, Client Pitches"},
        ],
    },
    "Embedded Systems Engineer": {
        "skills": {"embedded_systems": 9, "coding": 8, "electronics": 7, "debugging": 7, "systems_thinking": 6, "problem_solving": 7, "mathematics": 5},
        "salary": {"entry": "$65,000", "mid": "$105,000", "senior": "$150,000+"},
        "growth": ["Junior Embedded Dev", "Embedded Engineer", "Senior Embedded Eng", "Lead Embedded Eng", "Firmware Architect"],
        "description": "Design and program firmware for microcontrollers and embedded hardware systems.",
        "typical_degree": "Bachelor's in ECE/CS/EE",
        "demand": "high",
        "personality": ["detail-oriented", "hardware-savvy", "systematic"],
        "roadmap": [
            {"month": 1, "title": "C/C++ for Embedded", "tasks": ["C programming mastery", "Memory management", "Bit manipulation"], "stack": "C, GCC, Make", "concepts": "Pointers, Volatile, Endianness"},
            {"month": 2, "title": "Microcontrollers", "tasks": ["ARM Cortex-M programming", "Peripherals (GPIO, UART, SPI)", "Interrupt handling"], "stack": "STM32, Keil, OpenOCD", "concepts": "Registers, Interrupts, DMA"},
            {"month": 3, "title": "RTOS", "tasks": ["FreeRTOS tasks", "Synchronization primitives", "Real-time scheduling"], "stack": "FreeRTOS, Zephyr", "concepts": "Task Scheduling, Mutexes, Semaphores"},
            {"month": 4, "title": "Protocols & Communication", "tasks": ["I2C/SPI drivers", "CAN bus", "Wireless protocols"], "stack": "Logic Analyzer, Protocol Analyzers", "concepts": "Protocol Stacks, Error Handling"},
            {"month": 5, "title": "Testing & Debugging", "tasks": ["Unit testing embedded", "JTAG debugging", "Power optimization"], "stack": "Unity Test, J-Link, Oscilloscope", "concepts": "Test-Driven Embedded, Power Profiling"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Build embedded project", "Document hardware", "Interview prep"], "stack": "GitHub, Hackster.io, LinkedIn", "concepts": "Embedded Interviews, System Design"},
        ],
    },
    "Supply Chain Analyst": {
        "skills": {"analytical_thinking": 8, "data_analysis": 7, "business_acumen": 6, "communication": 6, "problem_solving": 6, "excel": 6, "process_optimization": 6, "sql": 4},
        "salary": {"entry": "$50,000", "mid": "$80,000", "senior": "$115,000+"},
        "growth": ["Junior Analyst", "Supply Chain Analyst", "Senior Analyst", "Supply Chain Manager", "VP of Supply Chain"],
        "description": "Optimize supply chain operations through data analysis, forecasting, and process improvement.",
        "typical_degree": "Bachelor's in Business/Operations/Industrial Engineering",
        "demand": "medium",
        "personality": ["analytical", "process-oriented", "detail-minded"],
        "roadmap": [
            {"month": 1, "title": "Supply Chain Basics", "tasks": ["SCM fundamentals", "Inventory models", "Demand forecasting"], "stack": "Excel, SAP basics", "concepts": "EOQ, Safety Stock, Bullwhip Effect"},
            {"month": 2, "title": "Data & Analytics", "tasks": ["SQL for logistics data", "KPI dashboards", "Trend analysis"], "stack": "SQL, Power BI, Excel", "concepts": "OTIF, Fill Rate, Lead Time"},
            {"month": 3, "title": "Process Optimization", "tasks": ["Value stream mapping", "Lean principles", "Six Sigma basics"], "stack": "Visio, Minitab", "concepts": "Lean, Six Sigma, Kaizen"},
            {"month": 4, "title": "ERP & Systems", "tasks": ["SAP modules", "WMS basics", "System integration"], "stack": "SAP, Oracle, NetSuite", "concepts": "ERP, MRP, WMS"},
            {"month": 5, "title": "Strategic Planning", "tasks": ["Network design", "Vendor management", "Risk assessment"], "stack": "Llamasoft, AnyLogic", "concepts": "Network Optimization, Sourcing"},
            {"month": 6, "title": "Certification & Career", "tasks": ["APICS CSCP prep", "Case studies", "Interview prep"], "stack": "APICS, LinkedIn, Notion", "concepts": "CSCP, Supply Chain Interviews"},
        ],
    },
    "NLP Engineer": {
        "skills": {"nlp": 9, "machine_learning": 8, "python": 8, "deep_learning": 7, "coding": 7, "mathematics": 6, "linguistics": 4, "problem_solving": 7},
        "salary": {"entry": "$80,000", "mid": "$140,000", "senior": "$200,000+"},
        "growth": ["Junior NLP Engineer", "NLP Engineer", "Senior NLP Eng", "NLP Architect", "Head of NLP"],
        "description": "Build systems that understand, generate, and process human language at scale.",
        "typical_degree": "Master's/PhD in CS/Linguistics/AI",
        "demand": "very_high",
        "personality": ["research-oriented", "analytical", "curious"],
        "roadmap": [
            {"month": 1, "title": "NLP Foundations", "tasks": ["Text preprocessing", "Tokenization", "Word embeddings"], "stack": "Python, NLTK, spaCy", "concepts": "TF-IDF, Word2Vec, GloVe"},
            {"month": 2, "title": "Deep Learning for NLP", "tasks": ["RNNs and LSTMs", "Attention mechanisms", "Seq2Seq models"], "stack": "PyTorch, TensorFlow", "concepts": "Sequence Modeling, Attention, Beam Search"},
            {"month": 3, "title": "Transformers & LLMs", "tasks": ["BERT fine-tuning", "GPT architectures", "Prompt engineering"], "stack": "Hugging Face, OpenAI, LangChain", "concepts": "Self-Attention, Pre-training, Few-shot"},
            {"month": 4, "title": "Applications", "tasks": ["Chatbot development", "Sentiment analysis", "Named entity recognition"], "stack": "Rasa, spaCy, Hugging Face", "concepts": "Intent Classification, NER, Dialogue"},
            {"month": 5, "title": "Production NLP", "tasks": ["Model optimization", "Serving at scale", "Evaluation metrics"], "stack": "ONNX, TorchServe, MLflow", "concepts": "Latency, Quantization, BLEU/ROUGE"},
            {"month": 6, "title": "Research & Career", "tasks": ["Reproduce NLP papers", "Build end-to-end system", "Interview prep"], "stack": "arXiv, GitHub, LeetCode", "concepts": "NLP Research, ML Design Interviews"},
        ],
    },
    "Graphic Designer": {
        "skills": {"graphic_design": 9, "creativity": 8, "visual_communication": 8, "design_thinking": 6, "communication": 5, "ui_design": 4, "prototyping": 4},
        "salary": {"entry": "$42,000", "mid": "$65,000", "senior": "$100,000+"},
        "growth": ["Junior Designer", "Graphic Designer", "Senior Designer", "Art Director", "Creative Director"],
        "description": "Create visual content for brands, marketing, and digital media using design principles.",
        "typical_degree": "Bachelor's in Graphic Design/Visual Arts",
        "demand": "medium",
        "personality": ["creative", "visual", "trend-aware"],
        "roadmap": [
            {"month": 1, "title": "Design Principles", "tasks": ["Color theory", "Typography", "Composition"], "stack": "Adobe Illustrator, Canva", "concepts": "Visual Hierarchy, Gestalt, Color Harmony"},
            {"month": 2, "title": "Digital Design", "tasks": ["Social media graphics", "Brand identity design", "Poster design"], "stack": "Adobe Photoshop, Illustrator", "concepts": "Brand Guidelines, Layout Design"},
            {"month": 3, "title": "Print & Production", "tasks": ["Print design", "Packaging design", "Pre-press preparation"], "stack": "InDesign, Illustrator", "concepts": "CMYK, Bleeds, Die Lines"},
            {"month": 4, "title": "Motion Graphics", "tasks": ["Animation basics", "Logo animation", "Social media motion"], "stack": "After Effects, Lottie", "concepts": "Keyframes, Easing, Motion Principles"},
            {"month": 5, "title": "Web & UI Design", "tasks": ["Website layouts", "UI components", "Responsive design"], "stack": "Figma, Adobe XD", "concepts": "Grid Systems, Component Design"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["Portfolio curation", "Case studies", "Freelance setup"], "stack": "Behance, Dribbble, Portfolio Site", "concepts": "Design Portfolio, Client Management"},
        ],
    },
    "Site Reliability Engineer": {
        "skills": {"devops": 8, "systems_administration": 8, "coding": 7, "cloud_computing": 7, "automation": 7, "systems_thinking": 7, "problem_solving": 7, "infrastructure": 6},
        "salary": {"entry": "$85,000", "mid": "$145,000", "senior": "$200,000+"},
        "growth": ["Junior SRE", "SRE", "Senior SRE", "Staff SRE", "Principal SRE"],
        "description": "Ensure system reliability, scalability, and performance through engineering and automation.",
        "typical_degree": "Bachelor's in CS/IT",
        "demand": "very_high",
        "personality": ["systematic", "resilient", "automation-focused"],
        "roadmap": [
            {"month": 1, "title": "SRE Foundations", "tasks": ["SRE principles (Google SRE book)", "SLIs/SLOs/SLAs", "Error budgets"], "stack": "Linux, Python, Bash", "concepts": "Toil, Error Budgets, Blameless Culture"},
            {"month": 2, "title": "Monitoring & Observability", "tasks": ["Metrics collection", "Distributed tracing", "Log aggregation"], "stack": "Prometheus, Jaeger, ELK", "concepts": "Three Pillars, Golden Signals, RED"},
            {"month": 3, "title": "Infrastructure as Code", "tasks": ["Terraform modules", "Configuration management", "GitOps"], "stack": "Terraform, Ansible, ArgoCD", "concepts": "IaC, Idempotency, Declarative Infra"},
            {"month": 4, "title": "Incident Management", "tasks": ["On-call setup", "Runbooks", "Postmortem writing"], "stack": "PagerDuty, Statuspage, Confluence", "concepts": "Incident Command, Postmortems, SLO Burn"},
            {"month": 5, "title": "Capacity & Performance", "tasks": ["Load testing", "Capacity planning", "Auto-scaling"], "stack": "k6, Kubernetes HPA, Grafana", "concepts": "Saturation, Utilization, Forecasting"},
            {"month": 6, "title": "Portfolio & Career", "tasks": ["SRE case studies", "Open source SRE tools", "Interview prep"], "stack": "GitHub, Google SRE Book", "concepts": "SRE Interviews, System Design"},
        ],
    },
    "Pharmaceutical Scientist": {
        "skills": {"pharmaceutical_knowledge": 8, "research": 8, "chemistry": 7, "data_analysis": 5, "attention_to_detail": 7, "analytical_thinking": 6, "writing": 5, "laboratory": 7},
        "salary": {"entry": "$65,000", "mid": "$95,000", "senior": "$140,000+"},
        "growth": ["Research Associate", "Scientist", "Senior Scientist", "Principal Scientist", "R&D Director"],
        "description": "Develop and test pharmaceutical compounds through rigorous research and regulatory processes.",
        "typical_degree": "Master's/PhD in Pharmacy/Chemistry/Biology",
        "demand": "medium",
        "personality": ["meticulous", "patient", "research-driven"],
        "roadmap": [
            {"month": 1, "title": "Drug Discovery", "tasks": ["Target identification", "High-throughput screening", "SAR analysis"], "stack": "PyMOL, ChemDraw, KNIME", "concepts": "Drug Targets, Lead Optimization"},
            {"month": 2, "title": "Formulation", "tasks": ["Dosage form design", "Excipient selection", "Stability testing"], "stack": "Dissolution apparatus, HPLC", "concepts": "Bioavailability, Pharmacokinetics"},
            {"month": 3, "title": "Analytical Methods", "tasks": ["HPLC method development", "Mass spectrometry", "Validation protocols"], "stack": "HPLC, LC-MS, UV-Vis", "concepts": "Method Validation, ICH Guidelines"},
            {"month": 4, "title": "Regulatory Science", "tasks": ["FDA submissions", "GMP compliance", "Clinical trial design"], "stack": "eCTD, EDMS systems", "concepts": "FDA, EMA, ICH, GMP, GLP"},
            {"month": 5, "title": "Data & Bioinformatics", "tasks": ["Clinical data analysis", "Biostatistics", "Pharmacovigilance"], "stack": "R, SAS, Python", "concepts": "Clinical Endpoints, Safety Reporting"},
            {"month": 6, "title": "Publication & Career", "tasks": ["Research publication", "Patent search", "Interview prep"], "stack": "PubMed, Google Scholar, SciFinder", "concepts": "Scientific Writing, IP, Regulatory"},
        ],
    },
    "Environmental Engineer": {
        "skills": {"civil_engineering": 5, "research": 6, "data_analysis": 5, "problem_solving": 6, "mathematics": 5, "attention_to_detail": 6, "communication": 5, "chemistry": 5},
        "salary": {"entry": "$55,000", "mid": "$80,000", "senior": "$115,000+"},
        "growth": ["Junior Env Engineer", "Environmental Engineer", "Senior Env Eng", "Lead Engineer", "Environmental Director"],
        "description": "Develop solutions for environmental problems including water, air, and soil quality.",
        "typical_degree": "Bachelor's in Environmental/Civil Engineering",
        "demand": "medium",
        "personality": ["mission-driven", "analytical", "sustainability-focused"],
        "roadmap": [
            {"month": 1, "title": "Environmental Science", "tasks": ["Water quality analysis", "Air pollution basics", "Environmental law"], "stack": "Excel, ArcGIS", "concepts": "EPA Regulations, Water Chemistry"},
            {"month": 2, "title": "Waste & Water Treatment", "tasks": ["Wastewater design", "Solid waste management", "Remediation"], "stack": "EPANET, Excel", "concepts": "Activated Sludge, Landfill Design"},
            {"month": 3, "title": "Environmental Modeling", "tasks": ["Air dispersion modeling", "Groundwater modeling", "Impact assessment"], "stack": "AERMOD, MODFLOW, GIS", "concepts": "EIA, Fate & Transport"},
            {"month": 4, "title": "Sustainability", "tasks": ["LCA analysis", "Green building", "Carbon footprint"], "stack": "SimaPro, LEED tools", "concepts": "LCA, Circular Economy, Net Zero"},
            {"month": 5, "title": "Regulatory & Compliance", "tasks": ["Permit applications", "Environmental auditing", "Monitoring programs"], "stack": "EPA databases, Compliance tools", "concepts": "NEPA, Clean Water Act, CERCLA"},
            {"month": 6, "title": "FE Exam & Career", "tasks": ["FE exam preparation", "Field experience", "Interview prep"], "stack": "NCEES, LinkedIn", "concepts": "PE Licensure, Environmental Consulting"},
        ],
    },
}


# ──────────────────────────────────────────────────────────────────────────────
# HELPER: Get all role names for display
# ──────────────────────────────────────────────────────────────────────────────

def get_all_role_names() -> list[str]:
    """Return a sorted list of all career role names in the taxonomy."""
    return sorted(ROLE_DATABASE.keys())

def get_role_data(role_name: str) -> Optional[dict]:
    """Get the full data dict for a specific role, or None if not found."""
    return ROLE_DATABASE.get(role_name)

# ──────────────────────────────────────────────────────────────────────────────
# SKILL DISPLAY NAMES (for prettier UI rendering)
# ──────────────────────────────────────────────────────────────────────────────

SKILL_DISPLAY_NAMES: dict[str, str] = {
    "coding": "Programming",
    "problem_solving": "Problem Solving",
    "systems_thinking": "Systems Thinking",
    "algorithmic_thinking": "Algorithmic Thinking",
    "frontend_development": "Frontend Development",
    "backend_development": "Backend Development",
    "database": "Database Management",
    "api_design": "API Design",
    "machine_learning": "Machine Learning",
    "deep_learning": "Deep Learning",
    "data_analysis": "Data Analysis",
    "statistics": "Statistics",
    "mathematics": "Mathematics",
    "communication": "Communication",
    "leadership": "Leadership",
    "teamwork": "Teamwork",
    "design_thinking": "Design Thinking",
    "ui_design": "UI Design",
    "ux_design": "UX Design",
    "cloud_computing": "Cloud Computing",
    "devops": "DevOps",
    "cybersecurity": "Cybersecurity",
    "product_thinking": "Product Thinking",
    "strategic_thinking": "Strategic Thinking",
    "analytical_thinking": "Analytical Thinking",
    "critical_thinking": "Critical Thinking",
    "debugging": "Debugging",
    "software_engineering": "Software Engineering",
    "mobile_development": "Mobile Development",
    "html_css": "HTML & CSS",
    "python": "Python",
    "sql": "SQL",
    "visualization": "Data Visualization",
    "automation": "Automation",
    "embedded_systems": "Embedded Systems",
    "robotics": "Robotics",
    "electronics": "Electronics",
    "research": "Research",
    "writing": "Technical Writing",
    "public_speaking": "Public Speaking",
    "project_management": "Project Management",
    "business_acumen": "Business Acumen",
    "financial_analysis": "Financial Analysis",
    "user_research": "User Research",
    "prototyping": "Prototyping",
    "creativity": "Creativity",
    "empathy": "Empathy",
    "networking": "Networking",
    "risk_assessment": "Risk Assessment",
    "ethical_hacking": "Ethical Hacking",
    "testing": "Software Testing",
    "quality_assurance": "Quality Assurance",
    "attention_to_detail": "Attention to Detail",
    "decision_making": "Decision Making",
    "stakeholder_management": "Stakeholder Management",
    "coordination": "Coordination",
    "planning": "Planning",
    "team_management": "Team Management",
    "agile_methodology": "Agile Methodology",
    "event_management": "Event Management",
    "nlp": "Natural Language Processing",
    "computer_vision": "Computer Vision",
    "infrastructure": "Infrastructure",
    "containerization": "Containerization",
    "security_engineering": "Security Engineering",
    "medical_knowledge": "Medical Knowledge",
    "patient_care": "Patient Care",
    "marketing": "Marketing",
    "negotiation": "Negotiation",
    "entrepreneurship": "Entrepreneurship",
    "git": "Git & Version Control",
    "logical_thinking": "Logical Thinking",
    "resilience": "Resilience",
    "adaptability": "Adaptability",
    "time_management": "Time Management",
    "self_management": "Self Management",
    "storytelling": "Storytelling",
    "documentation": "Documentation",
    "graphic_design": "Graphic Design",
    "visual_communication": "Visual Communication",
    "civil_engineering": "Civil Engineering",
    "mechanical_engineering": "Mechanical Engineering",
    "cad_design": "CAD Design",
    "manufacturing": "Manufacturing",
    "pharmaceutical_knowledge": "Pharmaceutical Knowledge",
    "chemistry": "Chemistry",
    "laboratory": "Laboratory Skills",
    "physics": "Physics",
}

def get_skill_display_name(skill_key: str) -> str:
    """Get a human-readable display name for a skill key."""
    return SKILL_DISPLAY_NAMES.get(skill_key, skill_key.replace("_", " ").title())
